version: '3.9'

services:
  db:
    image: mysql:latest
    container_name: progress-tracker-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 3
    networks:
      - app-network

  app:
    build: .
    container_name: progress-tracker-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/progress_tracker
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    ports:
      - "8081:8080"
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
