spring:
  datasource:
    username: root
    url: jdbc:mysql://db:3306/progress_tracker  # Use the service name 'db' instead of 'localhost'
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  application:
    name: progress-tracker-api
server:
  port: ${PORT:8080}
